---
title: "Data analysis: Intervention Phages"
output: html_notebook
---

## Experiment by ENVIRE partner: Poland

2 week-old chickens were purchased from farm with high resistance levels. Chickens were monitored 5 times: 
day 0 and weekly for 4 weeks. That day chickens were 42 days old. Starting from day 0, each 7-day litter 
was treated with sprayed phages at titer 10^10 pfu/ml. After chicken removal litter was pulled outside and 
is being stored.


```{r setup, include=FALSE}
source(here::here("visualization.R"))
source(here::here("utilities/data_interpolation.R"))
source(here::here("run_farm_module_parallel.R"))

inputs <- load_inputs()
n_sim  <- inputs$n_sim

# updating the input params
input_manual <- list(farm_size = 7.7,
                     day.max = 42)

input_interpolated <- interpolate_values()
input_manual <- c(input_manual, input_interpolated)

# simulating parallerl batches
parallel_output <-
  batch_simulator_parallel(farm_module = new.farm_module(input_list = load_inputs(input_manual)),
                           n_sim = n_sim)
output_avg      <- apply(parallel_output, c(1, 2), mean)

## Data from partners
C_ecoli_feces         <- c(4.11e6, 3.07e5, 5.51e6, 3.83e6, 1.39e6)
C_ecoli_feces_phages  <- c(5.37e5, 1.47e5, 1.67e6, 6.47e5, 5.64e4)
C_ecoli_litter        <- c(4.11e6, 1.03e6, 9.90e6, 9.90e5, 2.10e6)
C_ecoli_litter_phages <- c(5.37e5, 4.76e5, 6.20e4, 3.30e5, 4.00e4)

C_ctx_feces         <- c(3.04e3, 3.96e2, 4.63, 6.70e2, 0.00)
C_ctx_feces_phages  <- c(1.90e3, 2.49e2, 1.78e2, 3.13e02, 0.00)
C_ctx_litter        <- c(3.04e3, 4.50e4, 9.50e3, 6.10e4, 1.40e4)
C_ctx_litter_phages <- c(1.90e3, 1.13e3, 5.20e1, 7.10e2, 2.30e1)

day_idx <- c(1, 7, 14, 21, 27) + 14

## Plot for average (over broilers + iterations) excreted bacteria 

qoi1 <- log10(output_avg[, 3])[day_idx] # fecal samples
qoi1 <- log10(output_avg[, 1]/(output_avg[, 4]+inputs$litter_mass))[day_idx] # litter
qoi2 <- log10(C_ctx_feces)
qoi3 <- log10(C_ctx_feces_phages)

## function for plotting

plot_qoi <- function(qoi1, qoi2, qoi3, title){

  gg <- ggplot(data = data.frame(
  days = day_idx,  
  qoi1 = qoi1,  
  qoi2 = qoi2,
  qoi3 = qoi3
)) +
  geom_point(aes(x = days, y = qoi1, color = "Simulated"), size = 3) +  
  geom_line(aes(x = days, y = qoi1, color = "Simulated")) +   
  geom_point(aes(x = days, y = qoi2, color = "Untreated"), size = 3) + 
  geom_line(aes(x = days, y = qoi2, color = "Untreated")) + 
  geom_point(aes(x = days, y = qoi3, color = "Treated"), size = 3) + 
  geom_line(aes(x = days, y = qoi3, color = "Treated")) + 
  labs(
    title = title,
    subtitle = paste(dim(parallel_output)[3], "simulations"),
    x = "Days",
    y = "(log10 CFU/g)"
  ) +
  scale_color_manual(values = c("Simulated" = "red", "Treated" = "blue", "Untreated" = "black"),
                     labels = c("Simulated", "Treated", "Untreated"))

  return(gg)
}

```

```{r}

## Simulated ESBL E.coli vs experimental E.coli (in feces)
qoi1 <- log10(output_avg[, 3])[day_idx] 
qoi2 <- log10(C_ecoli_feces)
qoi3 <- log10(C_ecoli_feces_phages)
plot_qoi(qoi1, qoi2, qoi3, "Simulated ESBL E.coli vs experimental E.coli (in feces)")

## Simulated ESBL E.coli vs experimental CTX (in feces)
qoi1 <- log10(output_avg[, 3])[day_idx] 
qoi2 <- log10(C_ctx_feces)
qoi3 <- log10(C_ctx_feces_phages)
plot_qoi(qoi1, qoi2, qoi3, "Simulated ESBL E.coli vs experimental CTX (in feces)")

## Simulated ESBL E.coli vs experimental E.coli (in litter)
qoi1 <- log10(output_avg[, 1]/(output_avg[, 4]+inputs$litter_mass))[day_idx]
qoi2 <- log10(C_ecoli_litter)
qoi3 <- log10(C_ecoli_litter_phages)
plot_qoi(qoi1, qoi2, qoi3, "Simulated ESBL E.coli vs experimental E.coli (in litter)")

## Simulated ESBL E.coli vs experimental CTX (in litter)
qoi1 <- log10(output_avg[, 1]/(output_avg[, 4]+inputs$litter_mass))[day_idx]
qoi2 <- log10(C_ctx_litter)
qoi3 <- log10(C_ctx_litter_phages)
plot_qoi(qoi1, qoi2, qoi3, "Simulated ESBL E.coli vs experimental CTX (in litter)")

```
